service: e-commerce-api
frameworkVersion: "4"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    USER_POOL_CLIENT_ID:
      Fn::GetAtt:
        - userPoolClient
        - ClientId
    USER_POOL_ID:
      Ref: userPool

plugins:
  - serverless-esbuild

build:
  esbuild: false

functions:
  #users
  signUp:
    handler: src/user/web/signup.handler
    events:
      - httpApi:
          path: /auth/register
          method: POST

  confirmSignUp:
    handler: src/user/web/confirm.handler
    events:
      - httpApi:
          path: /auth/confirm
          method: POST

  login:
    handler: src/user/web/login.handler
    events:
      - httpApi:
          path: /auth/login
          method: POST

  refresh:
    handler: src/user/web/refresh.handler
    events:
      - httpApi:
          path: /auth/refresh
          method: POST

  # #products
  # createProduct:
  #   handler: src/product/create_product.handler
  #   events:
  #     - httpApi:
  #         path: /product
  #         method: POST

  # getProduct:
  #   handler: src/product/get_product.handler
  #   events:
  #     - httpApi:
  #         path: /product
  #         method: GET

  # updateProduct:
  #   handler: src/product/update_product.handler
  #   events:
  #     - httpApi:
  #         path: /product/{id}
  #         method: PATCH

  # searchProducts:
  #   handler: src/product/search_product.handler
  #   events:
  #     - httpApi:
  #         path: /product/search
  #         method: GET

  # #cart
  # getCart:
  #   handler: src/cart/get_cart.handler
  #   events:
  #     - httpApi:
  #         path: /cart/{id}
  #         method: GET

  # updateCart:
  #   handler: src/cart/update_cart.handler
  #   events:
  #     - httpApi:
  #         path: /cart
  #         method: PATCH

  # #checkout
  # checkout:
  #   handler: src/checkout/checkout.handler
  #   events:
  #     - httpApi:
  #         path: /checkout
  #         method: POST

resources: ${file(resources.yml)}

iam: ${file(iam.yml)}
